function getchannels() {
    let channeldb = [
        ["index.html", "NULL"],
        ["index2.html#https://sweet.tv/sk/tv/847-jednotka-hd", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch1.png"],
        ["index2.html#https://sweet.tv/sk/tv/848-dvojka-hd", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch2.png"],
        ["index2.html#https://sweet.tv/sk/tv/849-24-hd", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch3.png"],
        ["index2.html#https://sweet.tv/sk/tv/850-sport-hd", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch4.png"],
        ["index2.html#https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch5.png"],
        ["index2.html#https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch6.png"],
        ["index2.html#https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch7.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch8.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch9.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch10.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch11.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch12.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch13.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch14.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch15.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch16.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch17.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch18.png"],
        ["index3.html#https://nl.utako.moe/NHK_G/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch19.png"],
        ["index3.html#https://nl.utako.moe/NHK_E/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch20.png"],
        ["index3.html#https://nl.utako.moe/Nippon_TV/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch21.png"],
        ["index3.html#https://nl.utako.moe/TV_Asahi/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch22.png"],
        ["index3.html#https://nl.utako.moe/TBS/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch23.png"],
        ["index3.html#https://nl.utako.moe/TV_Tokyo/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch24.png"],
        ["index3.html#https://nl.utako.moe/Fuji_TV/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch25.png"],
        ["index3.html#https://nl.utako.moe/Tokyo_MX1/index.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v3/ch26.png"],
        ["index2.html#https://pluto.tv/us/live-tv/5f36d726234ce10007784f2a", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch28.png"],
        ["index3.html#https://content.uplynk.com/channel/1f93c13275024afb9e0ead299624073d.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch29.png"],
        ["index2.html#https://www.wwlp.com/watch-live/", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch30.png"],
        ["index2.htmlhttp://v2.weatherscan.net/", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch31.png"],
        ["index3.html#https://retroblast.tv/hls/stream.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch32.png"],
        ["index3.html#https://turnerlive.warnermediacdn.com/hls/live/2023183/aseast/noslate/VIDEO_1_5128000.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch33.png"],
        ["index3.html#https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8", "https://backend-mrdannyarmstrong.github.io/tvhora/v2/ch34.png"],
        ["index.html", "NULL"],
    ];
    return channeldb;
}

function getchinfo() {
    let chinfodb = [
        ["Channel Name", "Channel Description"],
        ["RTVS 1", "Všeobecný obsah"],
        ["RTVS 2", "Všeobecný a vzdelávací obsah"],
        ["RTVS 24", "Správy 24 hodín denne, 7 dní v týždni"],
        ["RTVS SPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["TV JOJ", "Televízne programy a filmy"],
        ["JOJ Plus", "Americké televízne relácie"],
        ["JOJ WAU", "Prémiový televízny kanál"],
        ["JOJ SPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["JOJ 24", "Správy 24 hodín denne, 7 dní v týždni"],
        ["JOJ Family", "Rodinné relácie a filmy"],
        ["JOJ Cinema", "Filmy"],
        ["JOJKO", "kreslené filmy"],
        ["Marzika", "Rodinný obsah"],
        ["Doma", "Televízne relácie pre ženy"],
        ["Dajto", "Televízne relácie pre mužov"],
        ["CS History", "Historický kanál"],
        ["CS Film", "Filmový kanál"],
        ["CS Mystery", "Mysteriózne filmy"],z
        ["NHK-G", "一般的なコンテンツ"],
        ["NHK-E", "教育コンテンツ"],
        ["NTV", "テレビ番組とニュース"],
        ["TV Asahi", "バラエティ番組"],
        ["TBS", "テレビ番組"],
        ["TV Tokyo", "テレビ番組とアニメ"],
        ["Fuji TV", "テレビ番組とアニメ"],
        ["Tokyo MX", "アニメ"],
        ["NHK World", "Content about Japan in English"],
        ["Bob Ross", "Joy of Painting"],
        ["Newsy", "Non bias news 24/7"],
        ["WWLP", "Local News 24/7"],
        ["Weather Scan", "Weather info 24/7"],
        ["Cartoon Network", "Cartoons"],
        ["Adult Swim", "Cartoons for adults."],
        ["TNT", "Movies TV shows and sports"],
        ["Channel Name", "Channel Description"],
    ];
    return chinfodb;
}