function getchannels() {
    let channeldb = [
        ["index4.html", "NULL"],
        ["index2.html#https://sweet.tv/sk/tv/847-jednotka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch1.png"],
        ["index2.html#https://sweet.tv/sk/tv/848-dvojka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch2.png"],
        ["index2.html#https://sweet.tv/sk/tv/849-24-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch3.png"],
        ["index2.html#https://sweet.tv/sk/tv/850-sport-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch4.png"],
        ["index2.html#https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch5.png"],
        ["index2.html#https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch6.png"],
        ["index2.html#https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch7.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch8.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch9.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch10.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch11.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch12.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch13.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch14.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch15.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch16.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch17.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch18.png"],
        ["https://pluto.tv/us/live-tv/5f36d726234ce10007784f2a", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch19.png"],
        ["https://www.newsnationnow.com/news-nation-live/", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch20.png"],
        ["http://v1.weatherscan.net/", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch21.png"],
        ["index2.html#https://retroblast.tv/hls/stream.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch22.png"],
        ["index2.html#https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch23.png"],
        ["https://backend-mrdannyarmstrong.github.io/digivision/v1/yt/zen.html", "https://backend-mrdannyarmstrong.github.io/digivision/v1/ch24.png"],
    ];
    return channeldb;
}
