function getchannels() {
    let channeldb = [
        ["index4.html", "NULL"],
        ["index2.html#https://sweet.tv/sk/tv/847-jednotka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch1.png"],
        ["index2.html#https://sweet.tv/sk/tv/848-dvojka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch2.png"],
        ["index2.html#https://sweet.tv/sk/tv/849-24-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch3.png"],
        ["index2.html#https://sweet.tv/sk/tv/850-sport-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch4.png"],
        ["index2.html#https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch5.png"],
        ["index2.html#https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch6.png"],
        ["index2.html#https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch7.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch8.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch9.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch10.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch11.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch12.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch13.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch14.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch15.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch16.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch17.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch18.png"],
        ["index2.html#https://embed.4gtv.tv/ftv/FTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch19.png"],
        ["index2.html#https://embed.4gtv.tv/ftv/FMTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch20.png"],
        ["index2.html#https://embed.4gtv.tv/ftv/FTTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch21.png"],
        ["index2.html#https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/pts.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch22.png"],
        ["index2.html#https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/ttvnews.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch23.png"],
        ["index2.html#https://www.ipcf.org.tw/zh-TW/Vod/Home", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch24.png"],
        ["index3.html#https://fastly.live.brightcove.com/6385235869112/ap-northeast-1/6282251407001/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJob3N0IjoiaWU4OWZvLmVncmVzcy5pdjNqZDgiLCJhY2NvdW50X2lkIjoiNjI4MjI1MTQwNzAwMSIsImVobiI6ImZhc3RseS5saXZlLmJyaWdodGNvdmUuY29tIiwiaXNzIjoiYmxpdmUtcGxheWJhY2stc291cmNlLWFwaSIsInN1YiI6InBhdGhtYXB0b2tlbiIsImF1ZCI6WyI2MjgyMjUxNDA3MDAxIl0sImp0aSI6IjYzODUyMzU4NjkxMTIifQ.4c-V1Ks3nBx9nRljtn5-jCNP_nLuWBbk-pw9BFWZfMQ/playlist-hls.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch25.png"],
        ["index3.html#https://amg00793-amg00793c6-firetv-us-4067.playouts.now.amagi.tv/playlist.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch26.png"],
        ["index2.html#https://www.newsnationnow.com/news-nation-live/", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch27.png"],
        ["index2.html#http://v2.weatherscan.net/", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch28.png"],
        ["index3.html#https://retroblast.tv/hls/stream.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch29.png"],
        ["index2.html#https://tvpass.org/channel/e-entertainment-usa-eastern-feed", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch30.png"],
        ["index3.html#https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch31.png"],
        ["index2.html#https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/zen.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch32.png"],
        ["index.html", "NULL"],
    ];
    return channeldb;
}

function getchinfo() {
    let chinfodb = [
        ["Channel Name", "Channel Description"],
        ["RTVS 1", "Všeobecný obsah"],
        ["RTVS 2", "Všeobecný a vzdelávací obsah"],
        ["RTVS 24", "Správy 24 hodín denne, 7 dní v týždni"],
        ["RTVS SPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["TV JOJ", "Televízne programy a filmy"],
        ["JOJ Plus", "Americké televízne relácie"],
        ["JOJ WAU", "Prémiový televízny kanál"],
        ["JOJ SPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["JOJ 24", "Správy 24 hodín denne, 7 dní v týždni"],
        ["JOJ Family", "Rodinné relácie a filmy"],
        ["JOJ Cinema", "Filmy"],
        ["JOJKO", "kreslené filmy"],
        ["Marzika", "Rodinný obsah"],
        ["Doma", "Televízne relácie pre ženy"],
        ["Dajto", "Televízne relácie pre mužov"],
        ["CS History", "Historický kanál"],
        ["CS Film", "Filmový kanál"],
        ["CS Mystery", "Mysteriózne filmy"],
        ["FTV", "綜合內容。"],
        ["FTV一", "綜藝節目和新聞。"],
        ["FTV台灣", "文化生活類節目。"],
        ["PTS", "面向公眾的綜合內容。"],
        ["TTV訊息", "全天候新聞。"],
        ["台灣原住民頻道", "原住民電視節目。"],
        ["Taiwan+", "Content about Taiwan in English. 英文台灣相關內容。"],
        ["BBC Earth", "Nature Documentaries"],
        ["News Nation", "Non bias news 24/7"],
        ["Weather Scan", "Weather info 24/7"],
        ["Cartoon Network", "Cartoons"],
        ["E!", "TV Shows and Movies"],
        ["TNT", "Movies TV shows and sports"],
        ["Tao Music", "Traditional Chinese music 24/7"],
        ["Channel Name", "Channel Description"],
    ];
    return chinfodb;
}

function getwebchannels() {
    let channeldb = [
        ["https://sweet.tv/sk/tv/847-jednotka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch1.png"],
        ["https://sweet.tv/sk/tv/848-dvojka-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch2.png"],
        ["https://sweet.tv/sk/tv/849-24-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch3.png"],
        ["https://sweet.tv/sk/tv/850-sport-hd", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch4.png"],
        ["https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch5.png"],
        ["https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch6.png"],
        ["https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch7.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch8.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch9.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch10.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch11.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch12.png"],
        ["https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch13.png"],
        ["https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch14.png"],
        ["https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch15.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch16.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch17.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch18.png"],
        ["https://embed.4gtv.tv/ftv/FTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch19.png"],
        ["https://embed.4gtv.tv/ftv/FMTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch20.png"],
        ["https://embed.4gtv.tv/ftv/FTTV.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch21.png"],
        ["https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/pts.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch22.png"],
        ["https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/ttvnews.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch23.png"],
        ["https://www.ipcf.org.tw/zh-TW/Vod/Home", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch24.png"],
        ["index2.html#https://fastly.live.brightcove.com/6385235869112/ap-northeast-1/6282251407001/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJob3N0IjoiaWU4OWZvLmVncmVzcy5pdjNqZDgiLCJhY2NvdW50X2lkIjoiNjI4MjI1MTQwNzAwMSIsImVobiI6ImZhc3RseS5saXZlLmJyaWdodGNvdmUuY29tIiwiaXNzIjoiYmxpdmUtcGxheWJhY2stc291cmNlLWFwaSIsInN1YiI6InBhdGhtYXB0b2tlbiIsImF1ZCI6WyI2MjgyMjUxNDA3MDAxIl0sImp0aSI6IjYzODUyMzU4NjkxMTIifQ.4c-V1Ks3nBx9nRljtn5-jCNP_nLuWBbk-pw9BFWZfMQ/playlist-hls.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch25.png"],
        ["index2.html#https://amg00793-amg00793c6-firetv-us-4067.playouts.now.amagi.tv/playlist.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch26.png"],
        ["https://www.newsnationnow.com/news-nation-live/", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch27.png"],
        ["http://v2.weatherscan.net/", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch28.png"],
        ["index2.html#https://retroblast.tv/hls/stream.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch29.png"],
        ["https://tvpass.org/channel/e-entertainment-usa-eastern-feed", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch30.png"],
        ["index2.html#https://turnerlive.warnermediacdn.com/hls/live/2023168/tnteast/slate/VIDEO_0_3564000.m3u8", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch31.png"],
        ["https://backend-mrdannyarmstrong.github.io/digivision/v2/yt/zen.html", "https://backend-mrdannyarmstrong.github.io/digivision/v2/ch32.png"],
    ];
    return channeldb;
}
